apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: helloworld
build:
  artifacts:
    - image: helloworld
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
      - k8s.yaml
portForward:
  - resourceType: deployment
    resourceName: my-deployment
    namespace: default
    port: 8080
    localPort: 8080
